id: P007994
initial_creation_type: ocr
source_metadata:
  id: bdr:W3MS866
  title: རྟགས་ཀྱི་འཇུག་པའི་དགོངས་འགྲེལ་རབ་གསལ་སྣང་བ།
  author: ''
  volumes:
    85d8f41f64a64ba3970ba0298c0351e8:
      image_group_id: I3MS868
      title: ''
      volume_number: 1
      total_pages: 38
ebook_metadata:
  title: རྟགས་ཀྱི་འཇུག་པའི་དགོངས་འགྲེལ་རབ་གསལ་སྣང་བ།
  author: ''
  sku: P007994
  cover: cover.jpg
  layers:
  - pagination
